FROM openjdk:11

WORKDIR /app
ARG CONF_MYSQL_URL
ARG CONF_MYSQL_USERNAME
ARG CONF_MYSQL_PASSWORD
ARG CONF_REDIS_HOST
ARG CONF_REDIS_PORT
ARG CONF_REDIS_PASSWORD
ARG CONF_REDIS_DATABASE

ENV CONF_MYSQL_URL=${CONF_MYSQL_URL}
ENV CONF_MYSQL_USERNAME=${CONF_MYSQL_USERNAME}
ENV CONF_MYSQL_PASSWORD=${CONF_MYSQL_PASSWORD}

ENV CONF_REDIS_HOST=${CONF_REDIS_HOST}
ENV CONF_REDIS_PORT=${CONF_REDIS_PORT}
ENV CONF_REDIS_PASSWORD=${CONF_REDIS_PASSWORD}
ENV CONF_REDIS_DATABASE=${CONF_REDIS_DATABASE}

COPY ./packages/backend/platform-service/target/platform-service-1.0-SNAPSHOT.jar .

CMD ["java", "-jar", "platform-service-1.0-SNAPSHOT.jar"]
