/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconEpAvatar: typeof import('~icons/ep/avatar')['default']
    IconFormkitArrowup: typeof import('~icons/formkit/arrowup')['default']
    IconFormkitHelp: typeof import('~icons/formkit/help')['default']
    IconFormkitRight: typeof import('~icons/formkit/right')['default']
    IconHealthiconsChartLine: typeof import('~icons/healthicons/chart-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
