name: CD
on: push

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v3
        with:
          ref: dev
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: maven build, clean
        working-directory: ./packages/backend
        run: |
          mvn clean package
